profile::kubernetes::deployment_server::user_defaults:
  owner: mwdeploy
  group: wikidev
  mode: "0640"

profile::kubernetes::deployment_server::services:
  main:
    mathoid:
      usernames:
        - name: mathoid
        - name: mathoid-deploy
    zotero:
      usernames:
        - name: zotero
        - name: zotero-deploy
    blubberoid:
      usernames:
        - name: blubberoid
        - name: blubberoid-deploy
    eventgate-analytics:
      usernames:
        - name: eventgate-analytics
        - name: eventgate-analytics-deploy
    eventgate-main:
      usernames:
        - name: eventgate-main
        - name: eventgate-main-deploy
    citoid:
      usernames:
        - name: citoid
        - name: citoid-deploy
    cxserver:
      usernames:
        - name: cxserver
        - name: cxserver-deploy
    sessionstore:
      usernames:
        - name: sessionstore
        - name: sessionstore-deploy
    termbox:
      usernames:
        - name: termbox
        - name: termbox-deploy
    wikifeeds:
      usernames:
        - name: wikifeeds
        - name: wikifeeds-deploy
    echostore:
      usernames:
        - name: echostore
        - name: echostore-deploy
    eventgate-logging-external:
      usernames:
        - name: eventgate-logging-external
        - name: eventgate-logging-external-deploy
    eventstreams:
      usernames:
        - name: eventstreams
        - name: eventstreams-deploy
    eventstreams-internal:
      usernames:
        - name: eventstreams-internal
        - name: eventstreams-internal-deploy
    eventgate-analytics-external:
      usernames:
        - name: eventgate-analytics-external
        - name: eventgate-analytics-external-deploy
    changeprop:
      usernames:
        - name: changeprop
        - name: changeprop-deploy
    changeprop-jobqueue:
      usernames:
        - name: changeprop-jobqueue
        - name: changeprop-jobqueue-deploy
    proton:
      usernames:
        - name: proton
        - name: proton-deploy
    mobileapps:
      usernames:
        - name: mobileapps
        - name: mobileapps-deploy
    recommendation-api:
      usernames:
        - name: recommendation-api
        - name: recommendation-api-deploy
    push-notifications:
      usernames:
        - name: push-notifications
        - name: push-notifications-deploy
    api-gateway:
      usernames:
        - name: api-gateway
        - name: api-gateway-deploy
    apertium:
      usernames:
        - name: apertium
        - name: apertium-deploy
    linkrecommendation:
      usernames:
        - name: linkrecommendation
        - name: linkrecommendation-deploy
    similar-users:
      usernames:
        - name: similar-users
        - name: similar-users-deploy
    shellbox:
      usernames:
        - name: shellbox
        - name: shellbox-deploy
    shellbox-constraints:
      usernames:
        - name: shellbox-constraints
        - name: shellbox-constraints-deploy
    shellbox-media:
      usernames:
        - name: shellbox-media
        - name: shellbox-media-deploy
    shellbox-syntaxhighlight:
      usernames:
        - name: shellbox-syntaxhighlight
        - name: shellbox-syntaxhighlight-deploy
    shellbox-timeline:
      usernames:
        - name: shellbox-timeline
        - name: shellbox-timeline-deploy
    miscweb:
      usernames:
        - name: miscweb
        - name: miscweb-deploy
    mwdebug:
      usernames:
        - name: mwdebug
        - name: mwdebug-deploy
    tegola-vector-tiles:
      usernames:
        - name: tegola-vector-tiles
        - name: tegola-vector-tiles-deploy
    rdf-streaming-updater:
      usernames:
        - name: rdf-streaming-updater
        - name: rdf-streaming-updater-deploy
    toolhub:
      usernames:
        - name: toolhub
        - name: toolhub-deploy
    apple-search:
      usernames:
        - name: apple-search
        - name: apple-search-deploy
  ml-serve:
    revscoring-editquality:
      usernames:
        - name: revscoring-editquality
        - name: revscoring-editquality-deploy
          owner: root
          group: deploy-ml-service
    revscoring-draftquality:
      usernames:
        - name: revscoring-draftquality
        - name: revscoring-draftquality-deploy
          owner: root
          group: deploy-ml-service
    revscoring-articlequality:
      usernames:
        - name: revscoring-articlequality
        - name: revscoring-articlequality-deploy
          owner: root
          group: deploy-ml-service
    kubeflow-kfserving:
      usernames: []
      private_files:
        owner: 'root'
        group: 'root'
        mode: '640'
    knative-serving:
      usernames: []
      private_files:
        owner: 'root'
        group: 'root'
        mode: '640'

# Specified in the private repo in this form
#profile::kubernetes::deployment_server_secrets::services:
#    zotero:
#      staging:
#         somekey: somevalue
#      codfw:
#         somekey: somevalue
#      eqiad:
#         somekey: somevalue
# Tokens are mandatory or the user won't be defined.
# Tokens are per-user and should be specified in the private repo
# in this form:
#profile::kubernetes::deployment_server::tokens:
#  main:
#    mathoid:
#      token: dummy
# ...
#  ml-serve:
#    admin:
#      token: dummy
#    revscoring-editquality:
#      token: dummy
#
