groups:
- name: modules/profile/files/prometheus/rules_k8s.conf
  rules:
  - record: instance_operation_type:kubelet_runtime_operations_latency_microseconds:avg5m
    expr: sum by(instance) (rate(kubelet_runtime_operations_latency_microseconds_sum{job="k8s-node", operation_type!="exec_sync"}[5m]))
      / sum by(instance) (rate(kubelet_runtime_operations_latency_microseconds_count{job="k8s-node", operation_type!="exec_sync"}[5m]))
  - record: instance_verb:apiserver_request_latencies_summary:avg5m
    expr: sum by(instance, verb) (rate(apiserver_request_latencies_summary_sum{job="k8s-api"}[5m]))
      / sum by(instance, verb) (rate(apiserver_request_latencies_summary_count{job="k8s-api"}[5m]))
  - record: instance_operation:etcd_request_latencies_summary:avg5m
    expr: sum by(instance, operation) (rate(etcd_request_latencies_summary_sum{job="k8s-api"}[5m]))
      / sum by(instance, operation) (rate(etcd_request_latencies_summary_count{job="k8s-api"}[5m]))

  # service_runner_request_duration_seconds is being deprecated by new metric express_router_request_duration_seconds
  # These rules can be removed once all services use an updated service-template-node and expose
  # metrics directly through prometheus (instead of via prometheus-statsd-exporter bridge).
  - record: service_uri:service_runner_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(uri, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_uri:service_runner_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(uri, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_uri:service_runner_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(uri, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_method:service_runner_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(method, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_method:service_runner_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(method, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_method:service_runner_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(method, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_status:service_runner_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(status, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_status:service_runner_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(status, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_status:service_runner_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(status, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))

  # express_router_request_duration_seconds is emitted by services that use service-template-node.
  - record: service_uri:express_router_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(path, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_uri:express_router_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(path, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_uri:express_router_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(path, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_method:express_router_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(method, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_method:express_router_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(method, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_method:express_router_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(method, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_status:express_router_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(status, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_status:express_router_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(status, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_status:express_router_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(status, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))

- name: self
  rules:
    - record: job:up:avail
      expr: sum by (job) (up) / count by (job) (up)
