profile::contacts::role_contacts:
  - 'Observability SREs'

cluster: prometheus
profile::resolving::domain_search:
  - wikimedia.org
  - eqiad.wmnet
  - codfw.wmnet
  - esams.wmnet
  - ulsfo.wmnet
  - eqsin.wmnet
  - drmrs.wmnet
prometheus::server::mysqld_exporter::mysql::host: db1115.eqiad.wmnet
prometheus::server::mysqld_exporter::mysql::port: 3306
prometheus::server::mysqld_exporter::mysql::database: zarcillo
prometheus::server::mysqld_exporter::mysql::user: prometheus-mysqld-exporter
# prometheus::server::mysqld_exporter::mysql::password: stored on the private repo

profile::prometheus::k8s::staging::thanos: true
profile::prometheus::analytics::thanos: true
profile::prometheus::services::thanos: true
profile::prometheus::k8s::thanos: true

# Thanos will ask Prometheus (via Thanos Sidecar) for last 15d only
profile::prometheus::thanos::min_time: '-15d'

# The single host that's running Pushgateway.
# DNS prometheus-pushgateway.discovery.wmnet must match.
profile::prometheus::pushgateway_host: 'prometheus1003.eqiad.wmnet'

profile::lvs::realserver::use_conftool: true
profile::lvs::realserver::pools:
  prometheus:
    services:
      - prometheus@analytics
      - prometheus@global
      - prometheus@k8s
      - prometheus@k8s-staging
      - prometheus@k8s-mlserve
      - prometheus@ops
      - prometheus@services
