nagios_group: analytics_eqiad
cluster: analytics
profile::admin::groups:
  - analytics-admins

# Database password will be filled added in profile::superset from the
# profile::superset::database_password hiera variable stored in the private repo.
profile::superset::database_uri: mysql://superset_staging@an-coord1001.eqiad.wmnet/superset_staging?ssl_ca=/etc/ssl/certs/Puppet_Internal_CA.pem
profile::superset::workers: 8
profile::superset::ldap_proxy_enabled: true
profile::superset::proxy::x_forwarded_proto: 'http'
profile::superset::proxy::ferm_srange: '($CACHES $ANALYTICS_NETWORKS)'
profile::superset::enable_cas: false
# Disabling due to permission issue https://phabricator.wikimedia.org/T273850
# profile::superset::cache_uri: 'localhost'

profile::druid::turnilo::port: 9091
profile::druid::turnilo::druid_clusters:
  - name: druid-analytics-eqiad
    host: 'an-druid1001.eqiad.wmnet:8082'
    sourceListRefreshInterval: 15000
    sourceReintrospectInterval: 120000
    type: druid

profile::monitoring::notifications_enabled: false

profile::kerberos::keytabs::keytabs_metadata:
  - role: 'superset'
    owner: 'superset'
    group: 'superset'
    filename: 'superset.keytab'

# Context https://phabricator.wikimedia.org/T278353#6976509
profile::kerberos::client::dns_canonicalize_hostname: false

profile::memcached::version: 'present'
profile::memcached::port: 11211
profile::memcached::size: 256
profile::memcached::extended_options:
  - 'modern'

profile::contacts::role_contacts: ['Analytics SREs']
