profile::admin::groups:
  - wmcs-roots

contactgroups: wmcs-team
mgmt_contactgroups: wmcs-team-email

profile::openstack::eqiad1::horizon::puppet_git_repo_name: instance-puppet
profile::openstack::eqiad1::horizon::puppet_git_repo_user: instance-puppet-user
