fixtures:
    symlinks:
        cassandra: "#{source_dir}"
        apt: "#{source_dir}/../apt"
        stdlib: "#{source_dir}/../stdlib"
        profile: "#{source_dir}/../profile"
        systemd: "#{source_dir}/../systemd"
        wmflib: "#{source_dir}/../wmflib"
        java: "#{source_dir}/../java"
