fixtures:
    symlinks:
        jenkins: "#{source_dir}"
        apt: "../../../../apt"
        base: "../../../../base"
        alternatives: "../../../../alternatives"
        logrotate: "../../../../logrotate"
        monitoring: "../../../../monitoring"
        nrpe: "../../../../nrpe"
        rsyslog: "../../../../rsyslog"
        ssh: "../../../../ssh"
        stdlib: "../../../../stdlib"
        systemd: "../../../../systemd"
        wmflib: "../../../../wmflib"
