fixtures:
    symlinks:
        php: "#{source_dir}"
        debian: "../../../../debian"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
        alternatives: "../../../../alternatives"
