cluster: parsoid
profile::mediawiki::php::php_version: "7.2"
profile::mediawiki::webserver::has_tls: false
has_lvs: false

# Bump the connections per backend to 5 in mcrouter, see T203786
profile::mediawiki::mcrouter_wancache::num_proxies: 5
# bail out in case a long-lasting C function is called and
# excimer can't throw its exception
profile::mediawiki::php::request_timeout: 201
profile::mediawiki::apc_shm_size: 4096M
profile::mediawiki::php::enable_fpm: true
profile::mediawiki::php::fpm_config:
  opcache.interned_strings_buffer: 96
  opcache.memory_consumption: 1024
  apc.ttl: 10
# Configure php-fpm restarts
profile::mediawiki::php::restarts::ensure: present
# We set the restart watermark at 200 MB, which is approximately how much
# opcache one full day of deployments consume.
profile::mediawiki::php::restarts::opcache_limit: 200
