profile::base::enable_contacts: true
profile::base::core_dump_pattern:  '/var/tmp/core/core.%h.%e.%p.%t'
profile::base::remote_syslog_tls:
  _default: &default
  - 'centrallog1001.eqiad.wmnet:6514'
  - 'centrallog2001.codfw.wmnet:6514'
  codfw: *default
  eqiad: *default
  esams: *default
  ulsfo: *default
  drmrs: *default
