fixtures:
    symlinks:
        squid: "#{source_dir}"
        logrotate: "../../../../logrotate"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
        systemd: "../../../../systemd"
