profile::kubernetes::master::service_cluster_ip_range: 10.192.76.0/24
profile::kubernetes::master::etcd_urls:
 - https://kubestagetcd2001.codfw.wmnet:2379
 - https://kubestagetcd2002.codfw.wmnet:2379
 - https://kubestagetcd2003.codfw.wmnet:2379
