fixtures:
    symlinks:
        icinga: "#{source_dir}"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
        nrpe: "../../../../nrpe"
        elasticsearch: "../../../../elasticsearch"
        monitoring: "../../../../monitoring"
        httpd: "../../../../httpd"
        acme_chief: "../../../../acme_chief"
