profile::kubernetes::master::service_cluster_ip_range: 10.64.72.0/24
profile::kubernetes::master::etcd_urls:
 - https://kubetcd1004.eqiad.wmnet:2379
 - https://kubetcd1005.eqiad.wmnet:2379
 - https://kubetcd1006.eqiad.wmnet:2379
